import { NextRequest, NextResponse } from "next/server";
import { getCurrentUser } from "@/lib/auth";
import { db } from "@/lib/db";
import { generateInvitationCode } from "@/lib/invitation-code";
import { z } from "zod";

const CreateInvitationSchema = z.object({
  targetEmail: z.string().email().optional().or(z.literal("")),
  message: z.string().optional(),
});

/**
 * POST /api/comptable/invitations
 * Generates a unique 48-hour invitation code (Scenario A)
 */
export async function POST(req: NextRequest) {
  const user = await getCurrentUser();
  if (!user || user.role !== "COMPTABLE") {
    return NextResponse.json({ error: "Non autorisé" }, { status: 401 });
  }

  let body: unknown = {};
  try {
    body = await req.json();
  } catch {}

  const parsed = CreateInvitationSchema.safeParse(body);
  if (!parsed.success) {
    return NextResponse.json({ error: "Données invalides" }, { status: 400 });
  }

  const { targetEmail, message } = parsed.data;

  // Generate unique code
  let code = generateInvitationCode();
  let existing = await db.comptableInvitation.findUnique({ where: { code } });
  while (existing) {
    code = generateInvitationCode();
    existing = await db.comptableInvitation.findUnique({ where: { code } });
  }

  // 48 hours validity
  const expiresAt = new Date(Date.now() + 48 * 60 * 60 * 1000);

  const invitation = await db.comptableInvitation.create({
    data: {
      type: "INVITATION",
      code,
      status: "PENDING",
      senderId: user.userId,
      targetEmail: targetEmail || null,
      message: message || null,
      expiresAt,
    },
  });

  return NextResponse.json(
    {
      success: true,
      invitation: {
        id: invitation.id,
        code: invitation.code,
        expiresAt: invitation.expiresAt,
        targetEmail: invitation.targetEmail,
        createdAt: invitation.createdAt,
      },
    },
    { status: 201 }
  );
}

/**
 * GET /api/comptable/invitations
 * List all invitations generated by this comptable
 */
export async function GET() {
  const user = await getCurrentUser();
  if (!user || user.role !== "COMPTABLE") {
    return NextResponse.json({ error: "Non autorisé" }, { status: 401 });
  }

  const invitations = await db.comptableInvitation.findMany({
    where: {
      senderId: user.userId,
      type: "INVITATION",
    },
    include: {
      recipient: { select: { id: true, name: true, email: true } },
    },
    orderBy: { createdAt: "desc" },
  });

  return NextResponse.json({ invitations });
}
